---
# tasks file for dbserver
#- name: deploy postgres
#  gather_facts: false
#  become: true
#  hosts: appdbs
#tasks:
- name: install postgres
  yum:
    name: postgresql-server
    state: latest
- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: check whether initdb execuded or not
  stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: p

# only run the next 2 tasks once!
- name: initilize postgres
  command: postgresql-setup initdb
  when: p.stat.readable is not defined
  run_once: yes
  ignore_errors: yes

- name: start postgres
  service:
    name: postgresql.service
    state: started
